language: node_js
node_js:
 - "0.10"

before_script:
 - npm install
 - ./node_modules/.bin/bower install
 - ./node_modules/.bin/grunt typescript

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
 - ./node_modules/.bin/grunt coveralls
